import type { Song } from './types';

/**
 * Seed discovery catalog. Audio is synthesized in the browser (Web Audio) so the
 * demo plays real sound without shipping binary audio. Artist uploads add real
 * `audioKind: 'file'` songs on top of these.
 *
 * synthSeed is the root frequency (Hz); the engine derives a short warm loop.
 */
export const SEED_CATALOG: Song[] = [
  {
    id: 'seed-nightbloom',
    title: 'Nightbloom',
    artist: 'Sable Iyer',
    artistSlug: 'sable-iyer',
    artwork: { from: '#7FE9BC', to: '#1C1F21' },
    genres: ['Electronic', 'Alternative'],
    releaseDate: '2026-03-14',
    explicit: false,
    isrc: 'USMM12600001',
    version: 'original',
    notes: 'Written at 3am on a borrowed OP-1. The bloom is the moment the bass drops out.',
    credits: [
      { role: 'Primary Artist', name: 'Sable Iyer' },
      { role: 'Producer', name: 'Sable Iyer' },
      { role: 'Mixing Engineer', name: 'D. Okafor' },
    ],
    durationSec: 26,
    audioKind: 'synth',
    synthSeed: 220,
    status: 'published',
    eligibleForDiscovery: true,
  },
  {
    id: 'seed-terracotta',
    title: 'Terracotta',
    artist: 'Mesa Lune',
    artistSlug: 'mesa-lune',
    artwork: { from: '#C8A24B', to: '#14120F' },
    genres: ['Soul', 'R&B'],
    releaseDate: '2026-01-09',
    explicit: false,
    version: 'original',
    notes: 'A love letter to the desert at dusk.',
    credits: [
      { role: 'Primary Artist', name: 'Mesa Lune' },
      { role: 'Songwriter', name: 'Mesa Lune' },
      { role: 'Mastering Engineer', name: 'K. Vance' },
    ],
    durationSec: 24,
    audioKind: 'synth',
    synthSeed: 174.6,
    status: 'published',
    eligibleForDiscovery: true,
  },
  {
    id: 'seed-glasshour',
    title: 'Glass Hour',
    artist: 'Novaa',
    artistSlug: 'novaa',
    artwork: { from: '#6FE3B4', to: '#0A0A0B' },
    genres: ['Pop', 'Electronic'],
    releaseDate: '2026-05-02',
    explicit: false,
    version: 'original',
    notes: 'Every synth here is a single take, warts and all.',
    credits: [
      { role: 'Primary Artist', name: 'Novaa' },
      { role: 'Producer', name: 'Ilo' },
    ],
    durationSec: 28,
    audioKind: 'synth',
    synthSeed: 261.6,
    status: 'published',
    eligibleForDiscovery: true,
  },
  {
    id: 'seed-cratedigger',
    title: 'Crate Digger',
    artist: 'Ø Kito',
    artistSlug: 'kito',
    artwork: { from: '#2FAE7A', to: '#101012' },
    genres: ['Hip-Hop', 'Jazz'],
    releaseDate: '2025-11-21',
    explicit: true,
    version: 'original',
    notes: 'Sampled from a record I found in a flooded basement in Lisbon.',
    credits: [
      { role: 'Primary Artist', name: 'Ø Kito' },
      { role: 'Producer', name: 'Ø Kito' },
      { role: 'Recording Engineer', name: 'S. Adeyemi' },
    ],
    durationSec: 22,
    audioKind: 'synth',
    synthSeed: 196,
    status: 'published',
    eligibleForDiscovery: true,
  },
  {
    id: 'seed-lowlight',
    title: 'Lowlight',
    artist: 'Marrow',
    artistSlug: 'marrow',
    artwork: { from: '#E8D19A', to: '#1C1F21' },
    genres: ['Alternative', 'Rock'],
    releaseDate: '2026-02-18',
    explicit: false,
    version: 'acoustic',
    notes: 'Recorded live to tape in one room with the lights off.',
    credits: [
      { role: 'Primary Artist', name: 'Marrow' },
      { role: 'Mixing Engineer', name: 'R. Neu' },
    ],
    durationSec: 25,
    audioKind: 'synth',
    synthSeed: 146.8,
    status: 'published',
    eligibleForDiscovery: true,
  },
  {
    id: 'seed-saudade',
    title: 'Saudade',
    artist: 'Corda',
    artistSlug: 'corda',
    artwork: { from: '#7FE9BC', to: '#2FAE7A' },
    genres: ['Latin', 'Jazz'],
    releaseDate: '2026-04-07',
    explicit: false,
    version: 'original',
    notes: 'For everyone who misses a place that no longer exists.',
    credits: [
      { role: 'Primary Artist', name: 'Corda' },
      { role: 'Featured Artist', name: 'Lia Reis' },
      { role: 'Producer', name: 'Corda' },
    ],
    durationSec: 27,
    audioKind: 'synth',
    synthSeed: 293.7,
    status: 'published',
    eligibleForDiscovery: true,
  },
];
